const carModels = [
  'Toyota Corolla',
  'Ford Focus',
  'Volkswagen Golf',
  'Honda Civic',
  'Chevrolet Silverado',
  'Ram 1500',
  'Toyota Camry',
  'Honda Accord',
  'Ford F-Series',
  'Nissan Altima',
  'Hyundai Elantra',
  'Chevrolet Equinox',
  'Jeep Cherokee',
  'Subaru Outback',
  'Toyota RAV4',
  'Jeep Grand Cherokee',
  'Ford Escape',
  'GMC Sierra',
  'Toyota Tacoma',
  'Honda CR-V',
  'Chevrolet Malibu',
  'Kia Optima',
  'Hyundai Sonata',
  'Ford Explorer',
  'Subaru Forester',
  'Nissan Rogue',
  'Jeep Wrangler',
  'Chevrolet Traverse',
  'Honda Pilot',
  'Ram 2500',
  'Toyota Highlander',
  'Ford Mustang',
  'GMC Terrain',
  'Nissan Sentra',
  'Subaru Crosstrek',
  'Jeep Renegade',
  'Chevrolet Colorado',
  'Hyundai Santa Fe',
  'Honda HR-V',
  'Toyota 4Runner',
  'Ford Edge',
  'GMC Acadia',
  'Nissan Pathfinder',
  'Subaru Impreza',
  'Jeep Compass',
  'Chevrolet Tahoe',
  'Honda Odyssey',
  'Toyota Tundra',
  'Ford Ranger',
  'Hyundai Tucson',
  'GMC Canyon',
  'Nissan Frontier',
  'Subaru Legacy',
  'Jeep Gladiator',
  'Chevrolet Suburban',
  'Honda Fit',
  'Toyota Sienna',
  'Ford Expedition',
  'Hyundai Kona',
  'GMC Yukon',
  'Nissan Murano',
  'Subaru Ascent',
  'Jeep Patriot',
  'Chevrolet Impala',
  'Honda Ridgeline',
  'Toyota Avalon',
  'Ford EcoSport',
  'Hyundai Accent',
  'GMC Savana',
  'Nissan Versa',
  'Subaru WRX',
  'Jeep Liberty',
  'Chevrolet Sonic',
  'Honda Clarity',
  'Toyota Sequoia',
  'Ford Transit',
  'Hyundai Veloster',
  'GMC Yukon XL',
  'Nissan Maxima',
  'Subaru BRZ',
  'Jeep Commander',
  'Chevrolet Bolt EV',
  'Honda Insight',
  'Toyota Yaris',
  'Ford Fusion',
  'Hyundai Palisade',
  'GMC Sierra HD',
  'Nissan Titan',
  'Jeep Comanche',
  'Chevrolet Camaro',
  'Honda Passport',
  'Toyota Prius',
  'Ford Flex',
  'Hyundai Genesis',
  'Nissan Kicks',
  'Subaru Baja',
  'Jeep Wagoneer',
  'Honda Element',
  'Ford Taurus',
  'Hyundai Venue',
  'Nissan Armada',
  'Subaru Loyale',
  'Jeep Scrambler',
  'Chevrolet Express',
  'Honda Crosstour',
  'Toyota Mirai',
  'Hyundai Entourage',
  'GMC Sierra 1500',
  'Nissan Cube',
  'Subaru XT',
  'Chevrolet HHR',
  'Honda S2000',
  'Toyota Prius c',
  'Hyundai Tiburon',
  'GMC Sierra 2500HD',
  'Nissan Juke',
  'Subaru SVX',
  'Chevrolet Volt',
  'Honda Del Sol',
  'Toyota Supra',
  'Ford Fiesta',
  'Hyundai Scoupe',
  'Nissan Quest',
  'Subaru GL',
  'Chevrolet Cruze',
  'Honda CR-Z',
  'Toyota MR2',
  'Ford GT',
  'Hyundai Excel',
  'GMC Sierra 3500',
  'Nissan Leaf',
  'Subaru Justy',
  'Chevrolet SSR',
  'Honda Prelude',
  'Toyota Cressida',
  'Ford Pinto',
  'Hyundai Stellar',
  'GMC Suburban',
  'Subaru BRAT',
  'Jeep Jeepster',
  'Chevrolet Aveo',
  'Honda NSX',
  'Toyota Matrix',
  'Ford Probe',
  'GMC Syclone',
  'Nissan 240SX',
  'Subaru Tribeca',
  'Jeep DJ',
  'Chevrolet Astro',
  'Toyota Echo',
  'Ford Thunderbird',
  'GMC Typhoon',
  'Nissan Stanza',
  'Jeep FC',
  'Chevrolet Caprice',
  'Toyota FJ Cruiser',
  'Ford Maverick',
  'GMC Sprint',
  'Nissan Almera',
  'Subaru WRX STI',
  'Jeep CJ',
  'Honda EV Plus',
  'Toyota Previa',
  'Ford Festiva',
  'Hyundai Ioniq',
  'GMC Vandura',
  'Nissan Micra',
  'Subaru XT6',
  'Toyota C-HR',
  'Ford Aspire',
  'Hyundai Grandeur',
  'GMC Caballero',
  'Nissan Note',
  'Toyota Venza',
  'Ford Contour',
  'Hyundai Starex',
  'GMC S-15',
  'Nissan Pulsar',
  'Subaru FF-1',
  'Chevrolet Lumina',
  'Ford Model A',
  'Hyundai Santamo',
  'GMC Envoy',
  'Honda Fit EV',
  'Toyota Corolla iM',
  'Ford Model T',
  'Hyundai i20',
];

export default carModels;
